# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34205a2e05a8762ba6480d5fb5214c17acc2381353d172661a854c4c914ae471195fd8dc59308c17abbeedefcf9e5e984da454794621eedcf95c152c4991e108

test:
  secret_key_base: 72e6e1e70c600dba284ed5d776876f54c8ad76762594cc78a31adda3173640940707568acd515d7461163fa2fbd44a1a5af29dc808b01f091df5593eaee8f70e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
